### ISSUE TITLE
Project build

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular2#7]
In the root folder, after a ```git clone```and a ```npm install``` the command ```ng build``` triggers the following error:
```
You have to be inside an angular-cli project in order to use the build command.
```
Here are my angular-cli informations:
```
angular-cli: 1.0.0-beta.28.3
node: 7.5.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

**Comment by vfedoriv** [comment]
Try update angular-cli to last version (1.0.0-beta.32.3)
https://github.com/angular/angular-cli#updating-angular-cli

**Comment by arey** [comment]
It's working with 1.0.0-beta.32.3 :-)
Could you please mention it to the readme.md?
<img width="1438" alt="spring-petclinic-angular2" src="https://cloud.githubusercontent.com/assets/838318/23174924/31ca720c-f85e-11e6-97e4-d1a56aa26a49.png">

**Comment by vfedoriv** [comment]
Ok.
Oops... navbar... what you bootstrap version ?

**Comment by vfedoriv** [comment]
readme updated, and fixed bootstrap version.

**Comment by arey** [comment]
Ok thanks, we may close this issue
