### ISSUE TITLE
Incorect navbar display

### ISSUE THREAD

**Issue by vfedoriv** [spring-petclinic/spring-petclinic-angular2#8]
Incorect navbar display with latest bootstrap version (4.0.0-alpha.6)

**Comment by vfedoriv** [comment]
correct in prev. version (4.0.0-alpha.5) and 3.3.7, so I just downgrade to stable v.3

**Comment by arey** [comment]
My Bootstrap version was 4.0.0-alpha.5

**Comment by vfedoriv** [comment]
hmm... interesting. 
can you try now, with last commit and npm update ?

**Comment by arey** [comment]
It's now working with Boostrap 3.3.7
<img width="1438" alt="spring-petclinic-angular2" src="https://cloud.githubusercontent.com/assets/838318/23208433/44238cbc-f8f5-11e6-9e47-ce43f17aaa8f.png">

**Comment by vfedoriv** [comment]
ok
